language: python
python:
  - 2.7
notifications:
  email:
    recipients:
    - steven.murray@curtin.edu.au

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

script:
  - nosetests --with-cov --cov mrpy --cov-config .coveragerc --logging-level=INFO
install:
  - sudo apt-get install python-numpy python-scipy
  - pip install mpmath
  - pip install cached_property

install:
  - conda install python=$TRAVIS_PYTHON_VERSION numpy scipy mpmath
  - conda install -c dan_blanchard python-coveralls nose-cov
  - pip install cached_property

deploy:
  user: stevenjeanette
  on:
    tags: true
  provider: pypi
  password:
    secure: lAM0ScaCdOTbixtJf908INAKIpVCIPLSu4ZpqSxdp0zzMsTJJoTLo00wlmzzjeQDsxqgpiUIvjnwlpdur7Q+IPmwFa9hkg4VX4Mqe0keoDaoUQaUzpypZqYF0w4egVgc62NnXCGg3B/JuqUFuyM692uvmjvokGmadXLevXvPaxM=


# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
