notifications:
  email:
    recipients:
    - steven.murray@curtin.edu.au
script: nosetests
install:
- sudo apt-get install python-numpy python-scipy
- pip install mpmath
deploy:
  user: stevenjeanette
  on:
    tags: true
  provider: pypi
  password:
    secure: lAM0ScaCdOTbixtJf908INAKIpVCIPLSu4ZpqSxdp0zzMsTJJoTLo00wlmzzjeQDsxqgpiUIvjnwlpdur7Q+IPmwFa9hkg4VX4Mqe0keoDaoUQaUzpypZqYF0w4egVgc62NnXCGg3B/JuqUFuyM692uvmjvokGmadXLevXvPaxM=
virtualenv:
  system_site_packages: true
language: python
before_install:
- sudo apt-get install gfortran
python:
- "2.7"
